-- video_db FULL schema (MySQL 8.0 compatible) + data
-- Generated by ChatGPT on 2025-09-09
SET NAMES utf8mb4;
SET time_zone = "+00:00";
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

CREATE DATABASE IF NOT EXISTS `video_db`
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `video_db`;

-- ========== TABLES (match data dump columns) ==========

-- categories: (id, name, description, color, created_at)
DROP TABLE IF EXISTS `categories`;
CREATE TABLE `categories` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(100) NOT NULL,
  `description` TEXT NULL,
  `color` VARCHAR(20) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY `uq_categories_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- users: (id, username, password, email, role, is_active, created_at, updated_at)
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `username` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(191) NOT NULL,
  `role` VARCHAR(20) NOT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `uq_users_email` (`email`),
  UNIQUE KEY `uq_users_username` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- videos: (id, title, description, video_id, category, thumbnail_url, views, likes, duration, software, extra, created_at, updated_at)
DROP TABLE IF EXISTS `videos`;
CREATE TABLE `videos` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `video_id` VARCHAR(64) NOT NULL,
  `category` VARCHAR(100) NULL,
  `thumbnail_url` VARCHAR(512) NULL,
  `views` INT NOT NULL DEFAULT 0,
  `likes` INT NOT NULL DEFAULT 0,
  `duration` INT NULL,
  `software` VARCHAR(100) NULL,
  `extra` VARCHAR(255) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY `idx_videos_category` (`category`),
  KEY `idx_videos_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ========== VIEWS (no DEFINER, match your dump) ==========
DROP VIEW IF EXISTS `featured_videos`;
CREATE OR REPLACE VIEW `featured_videos` AS
SELECT
  v.`id`,
  v.`title`,
  v.`description`,
  v.`video_id`,
  v.`category`,
  v.`thumbnail_url`,
  v.`views`,
  v.`likes`,
  v.`duration`,
  v.`software`,
  v.`created_at`
FROM `videos` v
ORDER BY v.`views` DESC, v.`likes` DESC
LIMIT 10;

DROP VIEW IF EXISTS `recent_videos`;
CREATE OR REPLACE VIEW `recent_videos` AS
SELECT
  v.`id`,
  v.`title`,
  v.`description`,
  v.`video_id`,
  v.`category`,
  v.`thumbnail_url`,
  v.`views`,
  v.`likes`,
  v.`duration`,
  v.`software`,
  v.`created_at`
FROM `videos` v
ORDER BY v.`created_at` DESC
LIMIT 20;

DROP VIEW IF EXISTS `user_stats`;
CREATE OR REPLACE VIEW `user_stats` AS
SELECT
  u.`role` AS `role`,
  COUNT(*) AS `total_users`,
  SUM(CASE WHEN u.`is_active` = 1 THEN 1 ELSE 0 END) AS `active_users`,
  MAX(u.`created_at`) AS `latest_user`
FROM `users` u
GROUP BY u.`role`;

DROP VIEW IF EXISTS `video_stats`;
CREATE OR REPLACE VIEW `video_stats` AS
SELECT
  v.`category` AS `category`,
  COUNT(*) AS `total_videos`,
  AVG(v.`views`) AS `avg_views`,
  MAX(v.`created_at`) AS `latest_video`
FROM `videos` v
WHERE v.`category` IS NOT NULL
GROUP BY v.`category`;

-- ========== DATA (from your dump) ==========
SET FOREIGN_KEY_CHECKS=0;

-- MariaDB dump 10.19  Distrib 10.4.32-MariaDB, for Win64 (AMD64)
--
-- Host: localhost    Database: video_db
-- ------------------------------------------------------
-- Server version	10.4.32-MariaDB

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Dumping data for table `categories`
--

LOCK TABLES `categories` WRITE;
/*!40000 ALTER TABLE `categories` DISABLE KEYS */;
INSERT INTO `categories` VALUES (1,'My Fav <3','My Fav <3 category videos','#ff69b4','2025-08-03 10:03:13'),(2,'Travel','Travel category videos','#4CAF50','2025-08-03 10:03:13'),(3,'Tutorial','Tutorial category videos','#2196F3','2025-08-03 10:03:13'),(4,'Trailer','Trailer category videos','#FF9800','2025-08-03 10:03:13'),(5,'Wedding','Wedding category videos','#00BCD4','2025-08-03 10:03:13'),(6,'Brand','Brand category videos','#9C27B0','2025-08-03 10:03:13'),(7,'Shorts','Shorts category videos','#F44336','2025-08-03 10:03:13');
/*!40000 ALTER TABLE `categories` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Dumping data for table `users`
--

LOCK TABLES `users` WRITE;
/*!40000 ALTER TABLE `users` DISABLE KEYS */;
INSERT INTO `users` VALUES (1,'admin','$2b$10$wSviAkUAUY/jwXm121UUnuc.c5lNjBZqPXJ7NujloWJe5g4CdALzC','admin@example.com','admin',1,'2025-07-30 08:08:35','2025-08-03 10:26:32'),(2,'admin2','$2b$10$wSviAkUAUY/jwXm121UUnuc.c5lNjBZqPXJ7NujloWJe5g4CdALzC','user1@example.com','admin',1,'2025-07-30 08:08:35','2025-08-03 10:26:32'),(3,'admin3','$2b$10$wSviAkUAUY/jwXm121UUnuc.c5lNjBZqPXJ7NujloWJe5g4CdALzC','admin3@gmail.com','admin',1,'2025-07-30 09:12:51','2025-08-03 10:26:32'),(4,'admin4','$2b$10$wSviAkUAUY/jwXm121UUnuc.c5lNjBZqPXJ7NujloWJe5g4CdALzC','admin4@example.com','admin',1,'2025-07-30 09:47:59','2025-08-03 10:26:32'),(6,'user1','$2b$10$rQZ8K9mN2pL3vX7yJ1hG4t.5uI6oP9qR0sA1bC2dE3fF4gH5iJ6kL7mN8oP9','user1@example.com','user',1,'2025-08-03 08:45:23','2025-08-03 08:45:23');
/*!40000 ALTER TABLE `users` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Dumping data for table `videos`
--

LOCK TABLES `videos` WRITE;
/*!40000 ALTER TABLE `videos` DISABLE KEYS */;
INSERT INTO `videos` VALUES (1,'Wedding test 2','ww','XqgyD0yadH0','Wedding','/uploads/thumbnail-1754222903149-179906261.jpg',0,0,NULL,'Capcut pc',NULL,'2025-08-03 12:08:23','2025-08-03 12:31:40'),(38,'VIDEO RECAP ','VIDEO RECAP DAN VAN 2025','i22tRDUj2zM','My Fav <3','/uploads/thumbnail-1754224445018-998138180.jpg',0,0,NULL,'Capcut pc',NULL,'2025-08-03 12:34:05','2025-08-03 12:34:05');
/*!40000 ALTER TABLE `videos` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2025-09-09 17:01:52

SET FOREIGN_KEY_CHECKS=1;
